# Run with cmake -P by the targets qau_setup() creates: -DQAU_MODE=<mode> -DQAU_CONFIG=<file generated by qau_setup>.
#
#   runtime   lay out the runtime folder next to the exes already in QAU_RUNTIME_DEST (the build tree)
#   deploy    copy QAU_EXES into a clean QAU_DIST_DIR, lay out the runtime, write package.json
#   package   deploy, then zip QAU_DIST_DIR into <QAU_PACKAGE_DIR>/<name>-<version>-win64.zip
#
# Runtime layout: every DLL in <dest>/<QAU_RUNTIME_DIR>, Qt plugins in .../plugins, QML modules in .../qml,
# plus <runtime>/<runtime>.manifest listing the DLLs (a private side-by-side assembly the exes' manifests
# depend on). The exes embed qt.conf pointing at plugins and QML, so nothing else is left at the top level.

cmake_minimum_required(VERSION 3.22)

if (NOT QAU_CONFIG OR NOT EXISTS "${QAU_CONFIG}")
    message(FATAL_ERROR "QauDeploy: QAU_CONFIG is not set or missing")
endif ()
include("${QAU_CONFIG}")

if (QAU_MODE STREQUAL "runtime")
    set(QAU_DEST "${QAU_RUNTIME_DEST}")
elseif (QAU_MODE STREQUAL "deploy" OR QAU_MODE STREQUAL "package")
    set(QAU_DEST "${QAU_DIST_DIR}")
else ()
    message(FATAL_ERROR "QauDeploy: unknown QAU_MODE \"${QAU_MODE}\"")
endif ()

# Top-level names that are never program files: user data and updater scratch (see InstallLayout::isProtectedPath).
set(protected_names update updater.json package.json logs ${QAU_PROTECTED})
list(TRANSFORM protected_names TOLOWER)

set(runtime "${QAU_DEST}/${QAU_RUNTIME_DIR}")

function(qau_is_protected relative out_var)
    string(REGEX REPLACE "/.*$" "" top "${relative}")
    string(TOLOWER "${top}" top)
    if (top IN_LIST protected_names)
        set(${out_var} TRUE PARENT_SCOPE)
    else ()
        set(${out_var} FALSE PARENT_SCOPE)
    endif ()
endfunction()

function(qau_json_escape text out_var)
    string(REPLACE "\\" "\\\\" text "${text}")
    string(REPLACE "\"" "\\\"" text "${text}")
    string(REPLACE "\r" "" text "${text}")
    string(REPLACE "\n" "\\n" text "${text}")
    string(REPLACE "\t" "\\t" text "${text}")
    set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(qau_deploy_runtime exes)
    file(MAKE_DIRECTORY "${runtime}")

    set(args ${exes}
        --libdir "${runtime}"
        --plugindir "${runtime}/plugins"
        --qml-deploy-dir "${runtime}/qml"
        --no-translations
        --verbose 0)
    if (QAU_QML_DIR)
        list(APPEND args --qmldir "${QAU_QML_DIR}")
    endif ()
    list(APPEND args ${QAU_WINDEPLOYQT_ARGS})

    execute_process(COMMAND "${QAU_WINDEPLOYQT}" ${args} RESULT_VARIABLE result ERROR_VARIABLE errors)
    if (NOT result EQUAL 0)
        message(FATAL_ERROR "QauDeploy: windeployqt failed (${result}):\n${errors}")
    endif ()

    # windeployqt doesn't reliably find the MinGW runtime outside a Qt shell.
    if (QAU_MINGW_BIN)
        foreach (dll libgcc_s_seh-1.dll libstdc++-6.dll libwinpthread-1.dll)
            if (EXISTS "${QAU_MINGW_BIN}/${dll}")
                file(COPY_FILE "${QAU_MINGW_BIN}/${dll}" "${runtime}/${dll}" ONLY_IF_DIFFERENT)
            endif ()
        endforeach ()
    endif ()

    # The exes embed their own qt.conf; one on disk would only add clutter.
    file(REMOVE "${QAU_DEST}/qt.conf")

    # Never next to the exe: the loader would look for the DLLs in the exe folder then.
    file(GLOB dlls RELATIVE "${runtime}" "${runtime}/*.dll")
    list(SORT dlls)
    set(QAU_RUNTIME_FILES "")
    foreach (dll ${dlls})
        string(APPEND QAU_RUNTIME_FILES "  <file name=\"${dll}\"/>\n")
    endforeach ()
    configure_file("${QAU_TEMPLATE_DIR}/runtime.manifest.in" "${runtime}/${QAU_RUNTIME_DIR}.manifest" @ONLY)
endfunction()

if (QAU_MODE STREQUAL "runtime")
    set(exes)
    foreach (exe ${QAU_EXES})
        get_filename_component(name "${exe}" NAME)
        list(APPEND exes "${QAU_DEST}/${name}")
    endforeach ()
    qau_deploy_runtime("${exes}")
    return()
endif ()

# Clean the destination, keeping user data, so stale files of older builds don't end up in the package.
if (EXISTS "${QAU_DEST}")
    file(GLOB entries RELATIVE "${QAU_DEST}" LIST_DIRECTORIES true "${QAU_DEST}/*")
    foreach (entry ${entries})
        qau_is_protected("${entry}" keep)
        if (NOT keep)
            file(REMOVE_RECURSE "${QAU_DEST}/${entry}")
        endif ()
    endforeach ()
endif ()
file(MAKE_DIRECTORY "${QAU_DEST}")

set(dest_exes)
foreach (exe ${QAU_EXES})
    get_filename_component(name "${exe}" NAME)
    file(COPY_FILE "${exe}" "${QAU_DEST}/${name}")
    list(APPEND dest_exes "${QAU_DEST}/${name}")
endforeach ()
qau_deploy_runtime("${dest_exes}")

# package.json: what the updater installs, and removes on the next update if it's gone.
file(GLOB_RECURSE all_files RELATIVE "${QAU_DEST}" "${QAU_DEST}/*")
set(files)
foreach (file ${all_files})
    qau_is_protected("${file}" skip)
    if (NOT skip)
        list(APPEND files "${file}")
    endif ()
endforeach ()
list(SORT files)

string(TIMESTAMP built "%Y-%m-%dT%H:%M:%S")
set(file_lines)
foreach (file ${files})
    qau_json_escape("${file}" escaped)
    list(APPEND file_lines "        \"${escaped}\"")
endforeach ()
list(JOIN file_lines ",\n" file_lines)

set(notes_line "")
if (QAU_NOTES_FILE AND EXISTS "${QAU_NOTES_FILE}")
    file(READ "${QAU_NOTES_FILE}" notes)
    string(STRIP "${notes}" notes)
    qau_json_escape("${notes}" notes)
    set(notes_line "    \"notes\": \"${notes}\",\n")
endif ()

qau_json_escape("${QAU_NAME}" name_escaped)
file(WRITE "${QAU_DEST}/package.json"
    "{\n"
    "    \"name\": \"${name_escaped}\",\n"
    "    \"version\": \"${QAU_VERSION}\",\n"
    "    \"minUpdaterProtocol\": ${QAU_PROTOCOL},\n"
    "    \"built\": \"${built}\",\n"
    "${notes_line}"
    "    \"files\": [\n${file_lines}\n    ]\n"
    "}\n")
list(LENGTH files file_count)
message(STATUS "QauDeploy: ${QAU_NAME} ${QAU_VERSION} -> ${QAU_DEST} (${file_count} files)")

if (QAU_MODE STREQUAL "package")
    file(MAKE_DIRECTORY "${QAU_PACKAGE_DIR}")
    set(zip "${QAU_PACKAGE_DIR}/${QAU_NAME}-${QAU_VERSION}-win64.zip")
    file(REMOVE "${zip}")
    # A file list rather than arguments: a package easily exceeds the Windows command line limit.
    set(list_file "${QAU_PACKAGE_DIR}/.package-files.txt")
    list(JOIN files "\n" file_list)
    file(WRITE "${list_file}" "${file_list}\npackage.json\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${zip}" --format=zip "--files-from=${list_file}"
        WORKING_DIRECTORY "${QAU_DEST}"
        RESULT_VARIABLE result)
    file(REMOVE "${list_file}")
    if (NOT result EQUAL 0)
        message(FATAL_ERROR "QauDeploy: zipping ${zip} failed")
    endif ()
    message(STATUS "QauDeploy: package ${zip}")
endif ()
